/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package back;

import javax.swing.JButton;

/**
 *
 * @author A45LB8.1
 */
public class Menu_Dokter extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Dokter
     */
    public Menu_Dokter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btntambahdokter = new javax.swing.JButton();
        btnhapusdokter = new javax.swing.JButton();
        btncaridokter = new javax.swing.JButton();
        btntampildokter = new javax.swing.JButton();
        btnmainmenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Menu Dokter");

        btntambahdokter.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btntambahdokter.setText("Tambah Data Dokter");

        btnhapusdokter.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnhapusdokter.setText("Hapus Data Dokter");

        btncaridokter.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btncaridokter.setText("Cari Data Lengkap Dokter");
        btncaridokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncaridokterActionPerformed(evt);
            }
        });

        btntampildokter.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btntampildokter.setText("Tampilkan Semua Dokter");

        btnmainmenu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnmainmenu.setText("Main Menu");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnmainmenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btntampildokter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnhapusdokter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btntambahdokter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btncaridokter)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabel1)))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btntambahdokter, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnhapusdokter, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btncaridokter, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btntampildokter, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnmainmenu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncaridokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncaridokterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncaridokterActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncaridokter;
    private javax.swing.JButton btnhapusdokter;
    private javax.swing.JButton btnmainmenu;
    private javax.swing.JButton btntambahdokter;
    private javax.swing.JButton btntampildokter;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    public JButton getBtncaridokter() {
        return btncaridokter;
    }

    public JButton getBtnhapusdokter() {
        return btnhapusdokter;
    }

    public JButton getBtnmainmenu() {
        return btnmainmenu;
    }

    public JButton getBtntambahdokter() {
        return btntambahdokter;
    }

    public JButton getBtntampildokter() {
        return btntampildokter;
    }
}
